apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  namespace: app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: app-frontend
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/web-app-repo:v1
          ports:
            - containerPort: 80
